apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 35.233.110.172
  selector:
    app: jenkinsdemo
  ports:
    - name: http
      port: 80
      targetPort: http
